### ISSUE TITLE
Broken links in MakeGenomeSuite

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/mango#486]
```
$ mvn test
...
MakeGenomeSuite:
Exception in thread "Thread-92" java.io.FileNotFoundException:
http://hgdownload.soe.ucsc.edu/goldenPath/anoGam1/database/refGene.txt.gz
...
Exception in thread "Thread-104" java.io.FileNotFoundException:
http://hgdownload.cse.ucsc.edu/goldenpath/anoGam1/database/cytoBand.txt.gz
```

Would it work to update these to the hg38 versions?
http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz
http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/cytoBand.txt.gz

Alternatively, we could use the GTF or GFF3 files from Ensembl and read them in as `Feature`s.
ftp://ftp.ensembl.org/pub/release-95/gff3/homo_sapiens

**Comment by akmorrow13** [comment]
Do the tests fail or does it just print the error? It should default to a different refGene file https://github.com/bigdatagenomics/mango/blob/master/mango-core/src/main/scala/org/bdgenomics/mango/util/GenomeConfig.scala#L111

**Comment by heuermh** [comment]
The broken links are only in the test suite, and it throws the exception but passes all the tests.

**Comment by akmorrow13** [comment]
That is expected. It throws a FileNotFound error because the file does not exist. It downloads an alternative refGene file after that.

**Comment by heuermh** [comment]
It looks like this one is supposed to fail

https://github.com/bigdatagenomics/mango/blob/master/mango-cli/src/test/scala/org/bdgenomics/mango/cli/MakeGenomeSuite.scala#L40

but it's not clear that this one should also fail

https://github.com/bigdatagenomics/mango/blob/master/mango-cli/src/test/scala/org/bdgenomics/mango/cli/MakeGenomeSuite.scala#L30

**Comment by akmorrow13** [comment]
Yes that is correct. 

https://github.com/bigdatagenomics/mango/blob/master/mango-cli/src/test/scala/org/bdgenomics/mango/cli/MakeGenomeSuite.scala#L40
Fails because the build does not exist.

https://github.com/bigdatagenomics/mango/blob/master/mango-cli/src/test/scala/org/bdgenomics/mango/cli/MakeGenomeSuite.scala#L30

Does not fail because the build does exist. It is missing primary files, however, so throws a FIleNotFoundException and defaults to a different file.

**Comment by heuermh** [comment]
Thanks!  Closing as WontFix
